### ISSUE TITLE
Non-latin characters are invisible in the nickname.

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#11]
**Describe the bug**
Setting your nickname to characters that are non-latin, causes them to be invisible.

**To Reproduce**
In the mod-settings.ini change your nickname to something that doesn't have latin characters, such as `анна`.

**Expected behavior**
Since the font and thus the glyph for the characters are there, it should render them. 

**Platform (please complete the following information):**
 - OS: Windows / Linux
 - Version: 10 / Arch

**Game Version:**
1.1.2

**Additional context**
This may or may not be related to [#44](https://github.com/Lojemiru/AM2R-Community-Updates/issues/44) on the main repo. But this occurs on Windows as well, while #44 doesn't.

**Comment by lassiterm** [comment]
The font I was using for names did not support non-latin characters. It's now using an internal font which does support them.
