### ISSUE TITLE
Set a Limit on how long the nicknames can be.

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#12]
**Describe the solution you'd like**
Make a set limit on how long the nickname can be.

**Media**
https://cdn.discordapp.com/attachments/539247998417502209/810087922438897694/d2021-02-13_10-58-26.mp4

**Note**
With a ***really long*** username (I had a 50MB mod-settings when testing) it is possible to create an out of memory crash.

**Comment by lassiterm** [comment]
Fixed by limiting to 15 characters.
