### ISSUE TITLE
Fullscreen Back in Time bug

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#14]
**Describe the bug**
Go in-game, go fullscreen with alt+enter, leave fullscreen with alt+enter. This will cause the game to softreset. A whole lot of fun bugs can be used with that.

**Media**
![pic](https://cdn.discordapp.com/attachments/446076173999407114/810236903071940648/unknown.png)
![pic2](https://cdn.discordapp.com/attachments/446076173999407114/810237081527648276/unknown.png)
![pic3](https://cdn.discordapp.com/attachments/539247998417502209/810236639808323614/unknown.png)

**Platform (please complete the following information):**
 - OS: Windows 10

**Game Version:**
1.1.2

**Comment by lassiterm** [comment]
Fixed.
