### ISSUE TITLE
Release Server via AppImage [LINUX]

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#21]
**Is your feature request related to a problem? Please describe.**
Since AM2R was recently moved over to being used as an AppImage, instead of needing to download all dependencies, the Server should be provided as one as well. Otherwise users would still have to download the dependencies.
And since the Server doesn't include any copyrighted assets, I don't think you're gonna get in trouble for just distributing an AppImage.

**Comment by lassiterm** [comment]
Server is now created as an AppImage. It will be distributed with the next release.
