### ISSUE TITLE
[BUG?] Queen is permanently dead from Savefile

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#22]
**Steps to reproduce**
If someone saves after the Queen was killed, but before the Metroid has been collected, the Queen will be permanently dead for everyone who is currently connected. Even if the players disconnect, and choose to play locally.

However, the sfx in the room before the queen still plays.

**Version tested on**
1.1.2

**Comment by lassiterm** [comment]
This behavior is expected, but the Queen sfx will no longer play if she is dead.
