### ISSUE TITLE
Softlock after game finish

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#23]
**Describe the bug**
If the one who enters the ship, pauses and selects to reload from save, all the other users will be in a permanent softlock. They can disconnect or connect, but they won't be able to pause or move, as the Game thinks you already beat the game
This will be fixed, if the one who entered the ship, enters the ship again.

**Expected behavior**
They should still be able to move.

**Platform (please complete the following information):**
 - OS: Windows
 - Version: 10

**Game Version:**
1.1.2

**Comment by lassiterm** [comment]
Player entering the ship cannot pause anymore because that doesn't make sense anyway. No more shenanigans :)
