### ISSUE TITLE
Have an installation method that does not require GM:S

### ISSUE THREAD

**Issue by Manfish64** [lassiterm/AM2R-Multitroid#26]
**Is your feature request related to a problem? Please describe.**
Licenses for GM:S 1.x are no longer being provided and GM:S 2 is only available for free as a 30 day trial. Users without a license for GM:S 1.x are only able to install AM2R-Multitroid in the 30 day time frame for GM:S 2, or buy a license for it.

**Describe the solution you'd like**
Have an installation method similar to the AM2R Community Updates, where a patch is applied to the game and GM:S is not used.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Lojemiru** [comment]
Uh... have you checked out the releases tab at all? The Community Updates AM2RLauncher lets you apply the Windows patch from the Releases tab, and there are separate installer patches for Android and Linux as well.

https://github.com/lassiterm/AM2R-Multitroid/releases/tag/v1.2.1

**Comment by Manfish64** [comment]
My bad, sorry for neglecting to read that. I was able to successfully install Multitroid using the AM2RLauncher.
