### ISSUE TITLE
AMD graphic cards on Linux Segmentation Fault on boot.

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#6]
**Describe the bug**
AMD cards on Linux create a Segmentation Fault error on boot. You need a workaround with the R600_DEBUG environment variable in order to boot. This affects both the Server and the Client application.
This *may* affect intel igpu users as well.

**To Reproduce**
Have an AMD graphic card, and boot the 

**Expected behavior**
The game boots fine without the workaround, just how it was in pre 1.1.1 Release

**Media**
[Here](https://cdn.discordapp.com/attachments/806611530438803458/808322785419984916/message.txt) is a log file from running the game. Running the game via GDB reveals a bit more info:
`[Switching to Thread 0xe55feac0 (LWP 15687)]
0xeb9d6dc2 in llvm::PMTopLevelManager::schedulePass(llvm::Pass*) () from /usr/lib32/libLLVM-11.so`
On every reboot, you get a different error, but they all stem from libLLVM

**Platform (please complete the following information):**
 - OS: Linux
 - Version: Arch

**Game Version:**
After 1.1.1

**Additional context**
According to Lojemiru, this seems to be something shader related. Maybe something relating to the compilation process as well? Since as far as I can tell, the Server application was a complete new project, that shares little to no code with AM2R.

**Comment by lassiterm** [comment]
Compiling with YYC removes the issue. Guess we're sticking with that for Linux sadly.
