### ISSUE TITLE
Mod Settings is never read from Appdata/config

### ISSUE THREAD

**Issue by Miepee** [lassiterm/AM2R-Multitroid#8]
**Describe the bug**
The "mod settings.ini" is never read from Appdata/config folder, even if the game doesn't have write access to the File

**To Reproduce**
Put the game in a read-only folder (or patch it as an AppImage), and then execute it.  

**Expected behavior**
According to the instructions `[t]he game will generate the file itself in home/<username./.config so you can still edit it.`, this however does not happen.

**Platform (please complete the following information):**
 - OS: Linux
 - Version: Arch
(This *should* happen on Windows as well though.

**Game Version:**
1.1.2

**Comment by lassiterm** [comment]
Fairly sure this has been fixed at some point.
